### ISSUE TITLE
Last dataset complaints

### ISSUE THREAD

**Issue by JDihlmann** [Mubias/BiasMuseum#36]
Der letze Datensatz war anscheinend ziemlich confusing, weil die farblichen Bilder zu viel Aufmerksamkeit auf sich gezogen haben. Die Leute fanden die Assoziation mit Nacht Bildern auch falsch.

**Comment by KatjaClaire** [comment]
also add corresponding complaint images!

**Comment by Vanessa-Ts** [comment]
Hab das mal mit ein paar Leuten getestet und es hängt wohl daran das DS 1 und DS3 im dritten level sehr ähnlich sind. Wenn man z.B das sehr bunte Bild in DS3 in Zeile 2, Reihe 4 mit dem aus DS 1 tauscht, wird es klarer was richtig ist.
