### ISSUE TITLE
Refine all texts

### ISSUE THREAD

**Issue by JDihlmann** [Mubias/BiasMuseum#48]
- [x] Re-Read all AI texts / hints / and button names 
- [x] Correct them as necessary
- [ ] Get in contact with the EKWler and let them read over the texts (One idea was to simply make screenshots and post them into the group with also a text document)
- [x] Add corrected texts to the codebase
- [ ] (Optional) contact museum also for a feedback loop

**Comment by JDihlmann** [comment]
Aktuelle Kritik an Text von Testern

- Erster Screen besser erklären / Eindeutiger geschrieben "Viele Leute kommen nicht rein ..."
- Button Text nicht trainieren sondern weiter oder was anderes
- Zweiter Screen zu viel Text, sollte eindeutiger sein 
- Zweiter Screen Button, "Ja, ich will helfen"

**Comment by KatjaClaire** [comment]
changed title: "Daten & KI"
