### ISSUE TITLE
Add people complaining

### ISSUE THREAD

**Issue by JDihlmann** [Mubias/BiasMuseum#61]
![Image](https://user-images.githubusercontent.com/9963865/207637213-e2351fde-9c89-4aeb-b18a-2f38a6c6ab12.png)

Select pictures of people that will complain after a wrong selection of dataset or cheer. 
Also at messages with the chat component 
Maybe animate the bubbles so that they appear smoothley

**Comment by KatjaClaire** [comment]
complaints added, last level still needs to be chosen (moved it to the corresponding issue)
