### ISSUE TITLE
Test app multiple times with testers

### ISSUE THREAD

**Issue by JDihlmann** [Mubias/BiasMuseum#62]
Test the app with family and friends ask them what they think and if they understand the topic.

**Comment by KatjaClaire** [comment]
evtl. Instruction in einfacher sprache zum klicken (für Kinder und Ältere etc.)

**Comment by KatjaClaire** [comment]
last dataset correct should be 3.

**Comment by KatjaClaire** [comment]
erkläre dass nur studierende ins clubhaus kommen

**Comment by KatjaClaire** [comment]
help button more obvious?
Einlasskontrolle ein Wort
Mehr info einfach mit "weiter"?
nicht: Spiel beenden
text bearbeiten in evaluation: Datensatz ausgewählt

**Comment by KatjaClaire** [comment]
1000 bilder schneller (am anfang) und smoother, evtl gerundet wenn nicht zu schwierig

**Comment by KatjaClaire** [comment]
am anfang: ein klick nötig bis chat anfängt?
