### ISSUE TITLE
Short Howto-summary of our object for the Hiwi in the museum

### ISSUE THREAD

**Issue by Vanessa-Ts** [Mubias/BiasMuseum#84]

**Comment by JDihlmann** [comment]
Oben rechte Ecke doppelt klicken um Fullscreen zu beenden

**Comment by Vanessa-Ts** [comment]
How To

Normal start-up:

Power on Mini-PC
Power on Monitor
Select the User „BiasObject“
Click on „Anmelden“
- App automatically starts -
If the app is not in the foreground by default:
	One Click on the browser window to bring the app to the front
Done!


If autostart does not work:

- Open cmd 
- Navigate to C:\Users\BiasObject\BiasMuseum\ by typing: cd BiasMuseum
- Enter and then type: serve -s build
- Press enter again

- Double Click on the desktop connection named „Bias – Chrome“ on the upper center of the screen


If nothing works:

Call us!!


Things that might be necessary but shouldn’t:

Exit Full Screen:
Double-click on the upper right corner


Exit Kiosk mode:
Press ALT + F4
(Only works with a keyboard)
